version: '3'

services:
    portainer:
        container_name: portainer
        image: portainer/portainer
        command: --no-auth -H tcp://localhost:2375
        ports:
            - "8080:9000"
        volumes:
            - /opt/portainer/data:/data
            - /var/run/docker.sock:/var/run/docker.sock
    volumes:
        portainer_data:
