version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        build:
            context: ../../dockerfile/
            dockerfile: nginx
        volumes:
            - ~/github:/code
            - ~/podman/confs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ~/podman/confs/nginx/snippets:/etc/nginx/snippets
            - ~/podman/certs:/etc/ssl/nginx
        restart: unless-stopped

    php:
        container_name: php
        image: php:fpm
        ports:
            - "9000:9000"
        build:
            context: ../../dockerfile/
            dockerfile: php
        volumes:
            - ~/github:/code
        restart: unless-stopped
