version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ~/github:/code
            - ~/docker/confs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ~/docker/confs/nginx/snippets:/etc/nginx/snippets
            - ~/docker/certs:/etc/ssl/nginx
        restart: unless-stopped
        
    php:
        container_name: php
        image: php:fpm
        ports:
            - "9000:9000"
        build:
            context: ../../dockerfile/
            dockerfile: php
        volumes:
            - ~/github:/code
            - ~/docker/confs/php/phplog.conf:/usr/local/etc/php-fpm.d/log.conf
            - ~/docker/confs/php/php.conf:/usr/local/etc/php-fpm.d/php.conf
            - ~/docker/confs/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        restart: unless-stopped
