version: "3"

services:
    mysql:
        container_name: mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        build:
            context: ../../dockerfile/
            dockerfile: mysql
        volumes:
            - ~/docker/data/mysql:/var/lib/mysql
            - ~/docker/confs/mysql/conf.d:/etc/mysql/conf.d
        environment:
            #- DB_HOST=mysql
            - MYSQL_ROOT_PASSWORD=senha
            - MYSQL_DATABASE=app
        restart: unless-stopped
        
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mysql
        ports:
            - "8082:80"
        volumes:
            - ~/docker/confs/phpmyadmin/phpmyadmin.php:/etc/phpmyadmin/config.user.inc.php
        environment:
            - PMA_HOST=mysql
        restart: unless-stopped
