version: "3"

services:
    mysql:
        container_name: mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        build:
            context: ../../dockerfile/
            dockerfile: mysql
        volumes:
            - ~/docker/data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=senha
            - MYSQL_DATABASE=app
        restart: unless-stopped
