# Inserts a blank line between shell prompts
add_newline = false

# black, red, green, blue, yellow, purple, cyan, white

format = "(bright-black bold)\\($username@$hostname $directory$php\\):(bold green)$status "

[hostname]
ssh_only = false
format =  "[$hostname](bold red)"
disabled = false

[username]
style_user = "bright-blue bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "yellow bold"
truncation_symbol = ".../"
read_only = " 🔒"

[cmd_duration]
min_time = 500
format = "Duração [$duration](bold yellow)"

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[php]
format = " PHP [🔹 $version](147 bold)"
disabled = false
